name: sphinx

channels:
  - conda-forge
dependencies:
  - python
  - pip
  - sphinx<6
  - myst-parser>=0.18
  - pydata-sphinx-theme==0.12.0
  - make
  - sphinx-togglebutton
  - pygments_anyscript
  - jinja2
  - ipython
  - linkify-it-py 
  - tomli
  - sphinx-copybutton
  - sphinxext-opengraph
  - pip:
    - sphinxcontrib-youtube
    - git+https://github.com/melund/sphinx-book-theme.git@anybody-tutorials
    - git+https://github.com/executablebooks/sphinx-design.git@6df47513e9

