name: sphinx

channels:
  - conda-forge
dependencies:
  - python
  - pip
  - sphinx
  - myst-parser
  - make
  - sphinx-book-theme
  - sphinx-design
  - sphinx-togglebutton
  - pygments_anyscript
  - jinja2
  - ipython
  - linkify-it-py 
  - tomli
  - sphinx-copybutton
  - pip:
    - sphinxext-opengraph
    - python-frontmatter
