name: sphinx

channels:
  - conda-forge
dependencies:
  - python
  - pip
  - sphinx
  - myst-parser>=0.18
  - make
#  - sphinx-book-theme
  - sphinx-design
  - sphinx-togglebutton
  - pygments_anyscript
  - jinja2
  - ipython
  - linkify-it-py 
  - tomli
  - sphinx-copybutton
  - pip:
    - sphinxext-opengraph
    - sphinxcontrib-youtube
    - git+https://github.com/pydata/pydata-sphinx-theme.git@main
    - git+https://github.com/executablebooks/sphinx-design.git@main

