name: sphinx

channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - sphinx
  - myst-parser
  - linkify-it-py
  - make
  - cloud_sptheme
  - pygments_anyscript
  - ipython
  - jinja2=3.0.3
  - pip:
    - sphinxext-opengraph
