name: sphinx

channels:
  - conda-forge
dependencies:
  - python
  - pip
  - sphinx<6
  - myst-parser>=0.18
  - pydata-sphinx-theme>=0.13
  - make
  - sphinx-togglebutton
  - pygments_anyscript
  - jinja2
  - ipython
  - linkify-it-py 
  - tomli
  - sphinx-copybutton
  - sphinxext-opengraph
  - sphinx-book-theme>=1.0
  - sphinx-design
  - sphinxcontrib-youtube



