name: sphinx

channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - sphinx<4.0
  - myst-parser=0.17.2
  - linkify-it-py=2.0.0
  - make
  - cloud_sptheme=1.10.1.post20200504175005
  - pygments_anyscript
  - ipython=8.4.0
  - jinja2=3.0.3

  - pip:
    - sphinxext-opengraph
